### PR TITLE
WEIS Refactor

### PR DESCRIPTION
**Pull request by JakeNunemaker**

### CODE REVIEW

**Comment by JakeNunemaker** [comment]
TODO:
- [x] Revise setup.py
- [x] Revise README
- [x] Add .github actions for tests and automatic deployment
- [x] @nikhar-abbas Can you add me to the PyPi project so I can finish setting up the GitHub action for auto deployment?
- [x] Add versioneer
- [x] Add PyPi API Token to secrets (needs to be merged first I think)
- [ ] What to do with old scripts that haven't been updated?

**Comment by nikhar-abbas** [comment]
> TODO:
> 
> * [x]  Revise setup.py
> * [x]  Revise README
> * [x]  Add .github actions for tests and automatic deployment
> * [x]  @nikhar-abbas Can you add me to the PyPi project so I can finish setting up the GitHub action for auto deployment?
> * [x]  Add versioneer
> * [x]  Add PyPi API Token to secrets
> * [ ]  What to do with old scripts that haven't been updated?

On the last bullet here, I think you can delete them unless they are providing something particularly useful.

**Comment by JakeNunemaker** [comment]
Ok this is pretty much ready to go with the exception of figuring out if we want to keep the last few post processing scripts and update them or build them back up as they are needed next.

I've done some revisions to the setup script, versioning and added some GitHub actions for automatic testing (there could be more added here in the future) and deployment. I also slimmed down the README a bit since a lot of it wasn't relevant anymore.

**Review by gbarter — APPROVED** [review]
This is all good from my end.  I leave it to Nikhar and Pietro to decide how they want to preserve the older code since this is slotted for `master`.

**Comment by JakeNunemaker** [comment]
That's a good point - I didn't think about submitting it against dev. Does that make more sense @nikhar-abbas @ptrbortolotti ?

**Comment by ptrbortolotti** [comment]
yeah maybe develop is a safer choice so that we can test it out in the next weeks

**Comment by JakeNunemaker** [comment]
Sounds good - I'll close this one and submit a new one to develop

**Pull request closed without merging**
